apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-newbridge
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-newbridge
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - {}
